CREATE SEQUENCE telefone_id_seq AS BIGINT START WITH 1 INCREMENT BY 1;
CREATE TABLE telefone (
    codigo BIGINT GENERATED BY DEFAULT AS SEQUENCE telefone_id_seq PRIMARY KEY ,
    ddd VARCHAR(2) NOT NULL ,
    numero VARCHAR(11) NOT NULL , 
    codigo_paciente BIGINT NOT NULL,
    FOREIGN KEY (codigo_paciente) REFERENCE pacienteModel(codigo)
)