CREATE SEQUENCE endereco_id_seq AS BIGINT START WITH 1 INCREMENT BY 1;
CREATE TABLE endereco (
    codigo BIGINT GENERATED BY DEFAULT AS SEQUENCE endereco_id_seq PRIMARY KEY ,
    
    logradoro VARCHAR(255) NOT NULL ,
    numero VARCHAR NOT NULL , 
    complemento VARCHAR(255),
    bairro VARCHAR(255) NOT NULL,
    cidade VARCHAR(255) NOT NULL,
    estado VARCHAR(2) NOT NULL,
    codigo_paciente BIGINT NOT NULL,

    FOREIGN KEY (codigo_paciente) REFERENCE pacienteModel(codigo)
)