CREATE SEQUENCE consulta_id_seq AS BIGINT START WITH 1 INCREMENT BY 1;
CREATE TABLE consulta (
    codigo BIGINT GENERATED BY DEFAULT AS SEQUENCE consulta_id_seq PRIMARY KEY ,
    
    medico VARCHAR(255) NOT NULL ,
    especialidade VARCHAR NOT NULL , 
    hora VARCHAR(5),
    dataAgenda VARCHAR(8) NOT NULL,
    dataConsulta VARCHAR(8) NOT NULL,
    protocolo VARCHAR(11) NOT NULL,
    codigo_paciente BIGINT NOT NULL,

    FOREIGN KEY (codigo_paciente) REFERENCE pacienteModel(codigo)
)